server:
  port: 8082
  servlet:
    context-path: /jike
    session:
      timeout:
  tomcat:
    uri-encoding: UTF-8
#  address: 10.228.13.218
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbjike
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
#freemarker静态资源配置
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    #thymeleaf静态资源配置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
#设定静态文件路径，js，css等
  mvc:
    static-path-pattern: /static/**
#配置i18n资源文件，供thymeleaf读取
  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8
